matrix:
    include:
        - env: ACTION=lint HOMEBREW_NO_AUTO_UPDATE=1
        - env: ACTION=carthage HOMEBREW_NO_AUTO_UPDATE=1
        - env: ACTION=iOS
        - env: ACTION=tvOS
        - env: ACTION=macOS
        - env: ACTION=swiftpm-macOS
        - env: ACTION=swiftpm-linuxOS
          os: linux
          sudo: required
          dist: trusty
          language: generic

os: osx
language: objective-c
osx_image: xcode9

script:
    - make install-$ACTION && make test-$ACTION
